# docker-compose.yml
version: "3.8"

services:
  keycloak-postgres:
    image: postgres:16
    container_name: keycloak-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - trabajo_final_keycloak_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: keycloak
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: mysecretpassword
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "3030:8080"
    depends_on:
      - keycloak-postgres
    networks:
      - app-network
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak-data/import:/opt/keycloak/data/import

  app-postgres:
    image: postgres:16
    container_name: app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: app_password
    ports:
      - "5433:5432"
    volumes:
      - trabajo_final_app_db_data:/var/lib/postgresql/data
      - ./init-app-postgres-db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio-server
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminsecret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network

  auth-service:
    build:
      context: ./backend
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - app-postgres
    networks:
      - app-network

  resources-service:
    build:
      context: ./resources-service
    container_name: resources-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      - minio
    networks:
      - app-network

  nginx:
    image: nginx:1.29.1-alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - resources-service
      - keycloak
      - minio
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  trabajo_final_keycloak_db_data:
  trabajo_final_app_db_data: