-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS logging_schema.error_logs
(
    id bigserial NOT NULL,
    "timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    service_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    error_message text COLLATE pg_catalog."default" NOT NULL,
    stack_trace text COLLATE pg_catalog."default",
    request_path text COLLATE pg_catalog."default",
    request_method character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT error_logs_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE logging_schema.error_logs
    IS 'Registra errores internos inesperados de la aplicación para auditoría y depuración.';

CREATE TABLE IF NOT EXISTS public.schema_migrations
(
    version bigint NOT NULL,
    dirty boolean NOT NULL,
    CONSTRAINT schema_migrations_pkey PRIMARY KEY (version)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id bigserial NOT NULL,
    uuid uuid NOT NULL,
    email character varying(200) COLLATE pg_catalog."default" NOT NULL,
    dni integer,
    nombre character varying(200) COLLATE pg_catalog."default" NOT NULL,
    segundo_nombre character varying(200) COLLATE pg_catalog."default",
    apellido character varying(200) COLLATE pg_catalog."default" NOT NULL,
    segundo_apellido character varying(200) COLLATE pg_catalog."default",
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    username character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (uuid),
    CONSTRAINT dni UNIQUE (dni),
    CONSTRAINT ids UNIQUE (uuid, id),
    CONSTRAINT uk863n1y3x0jalatoir4325ehal UNIQUE (username),
    CONSTRAINT uk_id UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS recursos_schema.recursos
(
    id serial NOT NULL,
    nombre character varying(200) COLLATE pg_catalog."default",
    descripcion character varying(200) COLLATE pg_catalog."default",
    href_photo character varying(300) COLLATE pg_catalog."default",
    estado estado_recurso NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT recursos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS reservas_schema.reserva
(
    id serial NOT NULL,
    nombre character varying(200) COLLATE pg_catalog."default",
    descripcion character varying COLLATE pg_catalog."default",
    estado reservas_schema.estado_reserva NOT NULL,
    solicitante_id integer NOT NULL,
    aprobador_o_cancelador_id integer,
    updated_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now(),
    fecha_hora_inicio timestamp with time zone,
    fecha_hora_fin timestamp with time zone,
    recurso_solicitado_id integer,
    CONSTRAINT reserva_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS reservas_schema.reserva
    ADD CONSTRAINT fk_aprobador_o_cancelador_id FOREIGN KEY (aprobador_o_cancelador_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS reservas_schema.reserva
    ADD CONSTRAINT fk_solicitante FOREIGN KEY (solicitante_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS reservas_schema.reserva
    ADD CONSTRAINT recurso_fk FOREIGN KEY (recurso_solicitado_id)
    REFERENCES recursos_schema.recursos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;