// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/recursos/ports/recursos_usecases.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/recursos/ports/recursos_usecases.go -destination=./internal/controller/http/v1/mocks/mock_recursos_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/evrone/go-clean-template/internal/entity"
	DTOs "github.com/evrone/go-clean-template/internal/usecase/recursos/ports/DTOs"
	criteria "github.com/evrone/go-clean-template/internal/usecase/recursos/ports/criteria"
	gomock "go.uber.org/mock/gomock"
)

// MockRecursoUseCase is a mock of RecursoUseCase interface.
type MockRecursoUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRecursoUseCaseMockRecorder
	isgomock struct{}
}

// MockRecursoUseCaseMockRecorder is the mock recorder for MockRecursoUseCase.
type MockRecursoUseCaseMockRecorder struct {
	mock *MockRecursoUseCase
}

// NewMockRecursoUseCase creates a new mock instance.
func NewMockRecursoUseCase(ctrl *gomock.Controller) *MockRecursoUseCase {
	mock := &MockRecursoUseCase{ctrl: ctrl}
	mock.recorder = &MockRecursoUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecursoUseCase) EXPECT() *MockRecursoUseCaseMockRecorder {
	return m.recorder
}

// CreateResource mocks base method.
func (m *MockRecursoUseCase) CreateResource(ctx context.Context, input DTOs.CreateResourceInput) (*entity.Recurso, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResource", ctx, input)
	ret0, _ := ret[0].(*entity.Recurso)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResource indicates an expected call of CreateResource.
func (mr *MockRecursoUseCaseMockRecorder) CreateResource(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResource", reflect.TypeOf((*MockRecursoUseCase)(nil).CreateResource), ctx, input)
}

// DeleteResource mocks base method.
func (m *MockRecursoUseCase) DeleteResource(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResource", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResource indicates an expected call of DeleteResource.
func (mr *MockRecursoUseCaseMockRecorder) DeleteResource(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResource", reflect.TypeOf((*MockRecursoUseCase)(nil).DeleteResource), ctx, id)
}

// GetResourceByID mocks base method.
func (m *MockRecursoUseCase) GetResourceByID(ctx context.Context, id int64) (*entity.Recurso, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceByID", ctx, id)
	ret0, _ := ret[0].(*entity.Recurso)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceByID indicates an expected call of GetResourceByID.
func (mr *MockRecursoUseCaseMockRecorder) GetResourceByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceByID", reflect.TypeOf((*MockRecursoUseCase)(nil).GetResourceByID), ctx, id)
}

// ListResources mocks base method.
func (m *MockRecursoUseCase) ListResources(ctx context.Context, arg1 criteria.Criteria) (*DTOs.PaginatedRecursosOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResources", ctx, arg1)
	ret0, _ := ret[0].(*DTOs.PaginatedRecursosOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResources indicates an expected call of ListResources.
func (mr *MockRecursoUseCaseMockRecorder) ListResources(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResources", reflect.TypeOf((*MockRecursoUseCase)(nil).ListResources), ctx, arg1)
}

// UpdateResource mocks base method.
func (m *MockRecursoUseCase) UpdateResource(ctx context.Context, id int64, input DTOs.UpdateResourceInput) (*entity.Recurso, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResource", ctx, id, input)
	ret0, _ := ret[0].(*entity.Recurso)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResource indicates an expected call of UpdateResource.
func (mr *MockRecursoUseCaseMockRecorder) UpdateResource(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResource", reflect.TypeOf((*MockRecursoUseCase)(nil).UpdateResource), ctx, id, input)
}
