// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/recursos/ports/photo_usecases.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/recursos/ports/photo_usecases.go -destination=./internal/controller/http/v1/mocks/mock_photo_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/evrone/go-clean-template/internal/entity"
	DTOs "github.com/evrone/go-clean-template/internal/usecase/recursos/ports/DTOs"
	gomock "go.uber.org/mock/gomock"
)

// MockPhotoUseCase is a mock of PhotoUseCase interface.
type MockPhotoUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoUseCaseMockRecorder
	isgomock struct{}
}

// MockPhotoUseCaseMockRecorder is the mock recorder for MockPhotoUseCase.
type MockPhotoUseCaseMockRecorder struct {
	mock *MockPhotoUseCase
}

// NewMockPhotoUseCase creates a new mock instance.
func NewMockPhotoUseCase(ctrl *gomock.Controller) *MockPhotoUseCase {
	mock := &MockPhotoUseCase{ctrl: ctrl}
	mock.recorder = &MockPhotoUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotoUseCase) EXPECT() *MockPhotoUseCaseMockRecorder {
	return m.recorder
}

// DeletePhoto mocks base method.
func (m *MockPhotoUseCase) DeletePhoto(ctx context.Context, resourceID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePhoto", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePhoto indicates an expected call of DeletePhoto.
func (mr *MockPhotoUseCaseMockRecorder) DeletePhoto(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePhoto", reflect.TypeOf((*MockPhotoUseCase)(nil).DeletePhoto), ctx, resourceID)
}

// UploadPhoto mocks base method.
func (m *MockPhotoUseCase) UploadPhoto(ctx context.Context, input DTOs.UploadPhotoInput) (*entity.Recurso, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPhoto", ctx, input)
	ret0, _ := ret[0].(*entity.Recurso)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPhoto indicates an expected call of UploadPhoto.
func (mr *MockPhotoUseCaseMockRecorder) UploadPhoto(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPhoto", reflect.TypeOf((*MockPhotoUseCase)(nil).UploadPhoto), ctx, input)
}
