// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/errorlog/ports/log_error_usecase.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/errorlog/ports/log_error_usecase.go -destination=./internal/controller/http/v1/mocks/mock_log_error_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ports "github.com/evrone/go-clean-template/internal/usecase/errorlog/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockLogErrorUseCase is a mock of LogErrorUseCase interface.
type MockLogErrorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLogErrorUseCaseMockRecorder
	isgomock struct{}
}

// MockLogErrorUseCaseMockRecorder is the mock recorder for MockLogErrorUseCase.
type MockLogErrorUseCaseMockRecorder struct {
	mock *MockLogErrorUseCase
}

// NewMockLogErrorUseCase creates a new mock instance.
func NewMockLogErrorUseCase(ctrl *gomock.Controller) *MockLogErrorUseCase {
	mock := &MockLogErrorUseCase{ctrl: ctrl}
	mock.recorder = &MockLogErrorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogErrorUseCase) EXPECT() *MockLogErrorUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockLogErrorUseCase) Execute(ctx context.Context, input ports.LogErrorInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockLogErrorUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockLogErrorUseCase)(nil).Execute), ctx, input)
}
