
package roles

// Roles Compuestos de Alto Nivel
const (
	SUPER_ADMIN    = "SUPER_ADMIN"
	ADMIN_USUARIOS = "ADMIN_USUARIOS"
	ADMIN_RECURSOS = "ADMIN_RECURSOS"
	USUARIO_COMUN  = "USUARIO_COMUN"
)

// Roles Granulares para Resources Service
const (
	// Recursos Controller
	POST_RECURSOS         = "POST_RECURSOS"
	DELETE_RECURSO_BY_ID  = "DELETE_RECURSO_BY_ID"
	PATCH_RECURSO_BY_ID   = "PATCH_RECURSO_BY_ID"
	GET_RECURSO_BY_ID     = "GET_RECURSO_BY_ID"
	GET_RECURSOS          = "GET_RECURSOS"
	POST_SEARCH_RECURSOS  = "POST_SEARCH_RECURSOS"
	POST_RECURSO_FOTO     = "POST_RECURSO_FOTO"
	DELETE_RECURSO_FOTO   = "DELETE_RECURSO_FOTO"
)
