// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/recursos/ports/persistant_port.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/recursos/ports/persistant_port.go -destination=./internal/usecase/recursos/usecases/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/evrone/go-clean-template/internal/entity"
	criteria "github.com/evrone/go-clean-template/internal/usecase/recursos/ports/criteria"
	gomock "go.uber.org/mock/gomock"
)

// MockRecursoRepository is a mock of RecursoRepository interface.
type MockRecursoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecursoRepositoryMockRecorder
	isgomock struct{}
}

// MockRecursoRepositoryMockRecorder is the mock recorder for MockRecursoRepository.
type MockRecursoRepositoryMockRecorder struct {
	mock *MockRecursoRepository
}

// NewMockRecursoRepository creates a new mock instance.
func NewMockRecursoRepository(ctrl *gomock.Controller) *MockRecursoRepository {
	mock := &MockRecursoRepository{ctrl: ctrl}
	mock.recorder = &MockRecursoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecursoRepository) EXPECT() *MockRecursoRepositoryMockRecorder {
	return m.recorder
}

// CountByCriteria mocks base method.
func (m *MockRecursoRepository) CountByCriteria(ctx context.Context, arg1 criteria.Criteria) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByCriteria", ctx, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByCriteria indicates an expected call of CountByCriteria.
func (mr *MockRecursoRepositoryMockRecorder) CountByCriteria(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByCriteria", reflect.TypeOf((*MockRecursoRepository)(nil).CountByCriteria), ctx, arg1)
}

// Delete mocks base method.
func (m *MockRecursoRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecursoRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecursoRepository)(nil).Delete), ctx, id)
}

// FindByCriteria mocks base method.
func (m *MockRecursoRepository) FindByCriteria(ctx context.Context, arg1 criteria.Criteria) ([]entity.Recurso, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCriteria", ctx, arg1)
	ret0, _ := ret[0].([]entity.Recurso)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCriteria indicates an expected call of FindByCriteria.
func (mr *MockRecursoRepositoryMockRecorder) FindByCriteria(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCriteria", reflect.TypeOf((*MockRecursoRepository)(nil).FindByCriteria), ctx, arg1)
}

// GetByID mocks base method.
func (m *MockRecursoRepository) GetByID(ctx context.Context, id int64) (*entity.Recurso, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Recurso)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRecursoRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRecursoRepository)(nil).GetByID), ctx, id)
}

// Save mocks base method.
func (m *MockRecursoRepository) Save(ctx context.Context, recurso *entity.Recurso) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, recurso)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRecursoRepositoryMockRecorder) Save(ctx, recurso any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRecursoRepository)(nil).Save), ctx, recurso)
}

// Update mocks base method.
func (m *MockRecursoRepository) Update(ctx context.Context, recurso *entity.Recurso) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, recurso)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRecursoRepositoryMockRecorder) Update(ctx, recurso any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecursoRepository)(nil).Update), ctx, recurso)
}
