// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/recursos/ports/file_storage_port.go
//
// Generated by this command:
//
//	mockgen -source=./internal/usecase/recursos/ports/file_storage_port.go -destination=./internal/usecase/recursos/usecases/mocks/mock_file_storage.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileStorageRepository is a mock of FileStorageRepository interface.
type MockFileStorageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageRepositoryMockRecorder
	isgomock struct{}
}

// MockFileStorageRepositoryMockRecorder is the mock recorder for MockFileStorageRepository.
type MockFileStorageRepositoryMockRecorder struct {
	mock *MockFileStorageRepository
}

// NewMockFileStorageRepository creates a new mock instance.
func NewMockFileStorageRepository(ctrl *gomock.Controller) *MockFileStorageRepository {
	mock := &MockFileStorageRepository{ctrl: ctrl}
	mock.recorder = &MockFileStorageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorageRepository) EXPECT() *MockFileStorageRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFileStorageRepository) Delete(ctx context.Context, fileURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, fileURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFileStorageRepositoryMockRecorder) Delete(ctx, fileURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFileStorageRepository)(nil).Delete), ctx, fileURL)
}

// Upload mocks base method.
func (m *MockFileStorageRepository) Upload(ctx context.Context, file *multipart.FileHeader, resourceID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, file, resourceID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockFileStorageRepositoryMockRecorder) Upload(ctx, file, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFileStorageRepository)(nil).Upload), ctx, file, resourceID)
}
