spring.application.name=ceniit-resource-manager


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:3030/realms/develop-spring-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:3030/realms/develop-spring-realm/protocol/openid-connect/certs

jwt.auth.converter.resource-id=ceniit-backend-develop
jwt.auth.converter.principle-attribute=preferred_username

logging.level.org.keycloak=DEBUG


keycloak.provider.config.server.url.url=http://localhost:3030
keycloak.provider.config.server.url=http://localhost:3030
keycloak.provider.config.realm.name=develop-spring-realm
keycloak.provider.config.realm.master=master
keycloak.provider.config.admin.cli=admin-cli
keycloak.provider.config.user.console=admin
keycloak.provider.config.password.console=admin
keycloak.provider.config.client.secret=admin