spring.application.name=ceniit-resource-manager

server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak.local:8080/realms/develop-spring-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak.local:8080/realms/develop-spring-realm/protocol/openid-connect/certs

jwt.auth.converter.resource-id=ceniit-backend-develop
jwt.auth.converter.principle-attribute=preferred_username
keycloak.client-id=ceniit-backend-develop


logging.level.org.keycloak=DEBUG


keycloak.provider.config.server.url.url=http://localhost:3030
keycloak.provider.config.server.url=http://localhost:3030
keycloak.provider.config.realm.name=develop-spring-realm
keycloak.provider.config.realm.master=master
keycloak.provider.config.admin.cli=admin-cli
keycloak.provider.config.user.console=admin
keycloak.provider.config.password.console=admin
keycloak.provider.config.client.secret=admin



# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/app_db
spring.datasource.username=app_user
spring.datasource.password=app_password
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
